import type { Metadata } from 'next';
import { Geist, Geist_Mono, Assistant } from 'next/font/google';
import './globals.css';
import Nav from './components/nav/Nav';
import dynamic from 'next/dynamic';
const Footer = dynamic(() => import('../app/components/footer/Footer'));

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const assistant = Assistant({
  subsets: ['hebrew', 'latin'],
  weight: ['400', '700'], // Regular and Bold
  variable: '--font-assistant',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="he" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${assistant.variable}`}>
        <div className="site-border-wrapper">
          <Nav />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
